apiVersion: v1
kind: Secret
metadata:
  name: {{ include "multichain-aggregator.fullname" . }}-frontend-env
  labels:
    {{- include "multichain-aggregator.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.frontend.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
---
