apiVersion: v1
kind: Secret
metadata:
  name: {{ include "multichain-aggregator.fullname" . }}-env
  labels:
    {{- include "multichain-aggregator.labels" . | nindent 4 }}
type: Opaque
data:
  MULTICHAIN_AGGREGATOR__DATABASE__CONNECT__URL: {{ .Values.config.databaseUrl | b64enc }}
{{- range $key, $value := .Values.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
---
