repos:
  - repo: local
    hooks:
      - id: helm-docs
        name: Helm Docs
        args: []
        description: >
          Uses 'helm-docs' to create documentation from the Helm chart's 'values.yaml' file,
          and inserts the result into a corresponding 'README.md' file.
        entry: jnorwood/helm-docs:v1.14.2
        files: (README\.md\.gotmpl|(Chart|requirements|values)\.yaml)$
        language: docker_image
        require_serial: true

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: helmlint
        name: Helm Lint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
