apiVersion: v1
kind: Secret
metadata:
  name: contracts-info-{{ include "blockscout-admin.fullname" . }}-env
  labels:
    {{- include "blockscout-admin.labels" . | nindent 4 }}
type: Opaque
data:
  CONTRACTS_INFO__DATABASE__URL: {{ .Values.contractsInfo.config.databaseUrl | b64enc }}
  CONTRACTS_INFO__API_KEYS__adminjs__KEY: {{ .Values.contractsInfo.config.apiKeys.adminjs | b64enc }}
  CONTRACTS_INFO__API_KEYS__extractor1__KEY: {{ .Values.contractsInfo.config.apiKeys.extractor1 | b64enc }}
{{- range .Values.contractsInfo.envFromSecret }}
  {{ .name }}: {{ .value | b64enc }}
{{- end }}
{{- range .Values.config.network }}
  CONTRACTS_INFO__CHAINS_CONFIG__NETWORKS__{{ .id }}__API_KEY: {{ .apiKey | b64enc }}
{{- end }}
---
