{{- if .Values.poolsExtractor.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: pools-extractor-{{ include "blockscout-admin.fullname" . }}-env
  labels:
    {{- include "blockscout-admin.labels" . | nindent 4 }}
type: Opaque
data:
{{- range .Values.poolsExtractor.envFromSecret }}
  {{ .name }}: {{ .value | b64enc }}
{{- end }}
{{- end }}
---
