apiVersion: v2
name: blockscout-complete
description: A Helm chart that combines Blockscout stack with Smart Contract Verification services

type: application

# This is the chart version
version: "0.1.3"

# This is the version number of the application being deployed
appVersion: "1.0.0"

# Dependencies
dependencies:
  - name: blockscout-stack
    version: "2.0.6"
    repository: "file://../blockscout-stack"
    condition: blockscout-stack.enabled
  - name: smart-contract-verification
    version: "0.1.3"
    repository: "file://../smart-contract-verification"
    condition: smart-contract-verification.enabled
maintainers:
  - name: AntiD2ta
  - name: nmjustinchan
