# Default values for blockscout-complete.
# This is a YAML-formatted file.

# Enable/disable the sub-charts
blockscout-stack:
  enabled: true
  # Override values for blockscout-stack chart
  # For detailed configuration options, refer to the original blockscout-stack chart

  # Network configuration
  config:
    network:
      id: 1
      name: Ether
      shortname: Ether
      currency:
        name: Ether
        symbol: ETH
        decimals: 18
        dualToken: false
    account:
      enabled: false
    testnet: false
    nameService:
      enabled: false
      url: ""
    prometheus:
      enabled: true
      ingressWhitelist:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
      blackbox:
        enabled: true
        path: /api/health

  # Blockscout backend configuration
  blockscout:
    enabled: true
    replicaCount: 1
    image:
      repository: blockscout/blockscout
      pullPolicy: IfNotPresent
      tag: "latest"

    # Integration with verification services
    extraEnv:
      - name: VERIFY_WITH_ETHBYTECODE_DB_ENABLED
        value: "true"
      - name: SMART_CONTRACT_VERIFIER_ENABLED
        value: "true"
      - name: SMART_CONTRACT_VERIFIER_URL
        value: "http://$(RELEASE_NAME)-smart-contract-verification-verifier:8050"
      - name: SMART_CONTRACT_VERIFIER_GRPC_URL
        value: "$(RELEASE_NAME)-smart-contract-verification-verifier:8051"
      - name: ETH_BYTECODE_DB_URL
        value: "http://$(RELEASE_NAME)-smart-contract-verification-eth-bytecode-db:8050"

    # Configure service for Blockscout
    service:
      type: ClusterIP
      port: 80

    # Configure ingress for Blockscout
    ingress:
      enabled: true
      className: "nginx"
      annotations: {}
      hostname: blockscout.example.com
      tls:
        enabled: true
      paths:
        - path: /api
          pathType: Prefix
        - path: /socket
          pathType: Prefix
        - path: /sitemap.xml
          pathType: Prefix
        - path: /public-metrics
          pathType: Prefix
        - path: /auth/auth0
          pathType: Exact
        - path: /auth/auth0/callback
          pathType: Exact
        - path: /auth/logout
          pathType: Exact

  # Frontend configuration
  frontend:
    enabled: true
    replicaCount: 2
    image:
      repository: ghcr.io/blockscout/frontend
      tag: latest
      pullPolicy: IfNotPresent

    # Frontend environment variables for verification integration
    extraEnv:
      - name: NEXT_PUBLIC_VERIFICATION_MICROSERVICE_URL
        value: "https://$(RELEASE_NAME)-smart-contract-verification-verifier:8050"

    # Configure service for Frontend
    service:
      type: ClusterIP
      port: 80

    # Configure ingress for Frontend
    ingress:
      enabled: true
      className: "nginx"
      annotations: {}
      hostname: blockscout.example.com
      tls:
        enabled: true
      paths:
        - path: /
          pathType: Prefix

  # Stats configuration
  stats:
    enabled: false

  # User-Ops Indexer configuration
  userOpsIndexer:
    enabled: false

smart-contract-verification:
  enabled: true
  # Override values for smart-contract-verification chart
  # For detailed configuration options, refer to the original smart-contract-verification chart

  # Sig Provider configuration
  sigProvider:
    replicaCount: 2
    image:
      repository: ghcr.io/blockscout/sig-provider
      pullPolicy: IfNotPresent
      tag: "latest"

    # Configure service for Sig Provider
    service:
      type: ClusterIP
      port: 8043

    # Configure ingress for Sig Provider
    ingress:
      enabled: true
      className: "nginx"
      annotations: {}
      hostname: sig-provider.example.com
      tls:
        enabled: true

  # Smart Contract Verifier configuration
  smartContractVerifier:
    replicaCount: 2
    image:
      repository: ghcr.io/blockscout/smart-contract-verifier
      pullPolicy: IfNotPresent
      tag: "latest"

    # Configure service for Smart Contract Verifier
    service:
      type: ClusterIP
      port: 8050

    # Configure ingress for Smart Contract Verifier
    ingress:
      enabled: true
      className: "nginx"
      annotations: {}
      hostname: verifier.example.com
      tls:
        enabled: true

    # Configure grpc service
    grpc:
      enabled: true
      port: 8051
      ingress:
        enabled: true
        className: "nginx"
        annotations: {}
        hostname: grpc-verifier.example.com
        tls:
          enabled: true

  # Eth Bytecode DB configuration
  ethBytecodeDb:
    enabled: true
    replicaCount: 1
    image:
      repository: ghcr.io/blockscout/eth-bytecode-db
      pullPolicy: IfNotPresent
      tag: "latest"

    # Configure service for Eth Bytecode DB
    service:
      type: ClusterIP
      port: 8050

    # Configure ingress for Eth Bytecode DB
    ingress:
      enabled: true
      className: "nginx"
      annotations: {}
      hostname: bytecode-db.example.com
      tls:
        enabled: true

    # Environment variables for integrating with other services
    extraEnv:
      - name: ETH_BYTECODE_DB__SERVER__HTTP__ADDR
        value: "0.0.0.0:8050"
      - name: ETH_BYTECODE_DB__VERIFICATION__VERIFIER_URLS__0
        value: "http://$(RELEASE_NAME)-smart-contract-verification-verifier:8050"

# Global configuration shared by all components
global:
  # Add any global configurations here if needed
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
