{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "autoscout.fullname" . }}-frontend
  labels:
    app: {{ include "autoscout.fullname" . }}-frontend
    {{- include "autoscout.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "autoscout.fullname" . }}-frontend
    {{- include "autoscout.selectorLabels" . | nindent 4 }}
{{- end }}
