---
{{- if not .Values.config.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "autoscout.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "autoscout.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.config.database.username | b64enc | quote }}
  password: {{ .Values.config.database.password | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "autoscout.fullname" . }}-github
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "autoscout.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.config.github.token | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "autoscout.fullname" . }}-auth0
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "autoscout.labels" . | nindent 4 }}
type: Opaque
data:
  client_id: {{ .Values.config.auth0.client_id | b64enc | quote }}
  management_client_id: {{ .Values.config.auth0.management.client_id | b64enc | quote }}
  management_secret: {{ .Values.config.auth0.management.secret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "autoscout.fullname" . }}-coinbase
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "autoscout.labels" . | nindent 4 }}
type: Opaque
data:
  api_key: {{ .Values.config.coinbase.api_key | b64enc | quote }}
  webhook_secret: {{ .Values.config.coinbase.webhook_secret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "autoscout.fullname" . }}-sendgrid
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "autoscout.labels" . | nindent 4 }}
type: Opaque
data:
  api_key: {{ .Values.config.sendgrid.api_key | b64enc | quote }}
---
{{- if .Values.config.envFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autoscout.fullname" . }}-env
  labels:
    {{- include "autoscout.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.config.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
