apiVersion: v1
kind: Secret
metadata:
  name: {{ template "quicknode-marketplace-integration.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quicknode-marketplace-integration.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.config.databaseUrl | b64enc | quote }}
  BASIC_AUTH_USERNAME_RPC: {{ .Values.config.basicAuthRPC.username | b64enc | quote }}
  BASIC_AUTH_PASSWORD_RPC: {{ .Values.config.basicAuthRPC.password | b64enc | quote }}
  BASIC_AUTH_USERNAME_REST: {{ .Values.config.basicAuthREST.username | b64enc | quote }}
  BASIC_AUTH_PASSWORD_REST: {{ .Values.config.basicAuthREST.password | b64enc | quote }}
  BASIC_AUTH_USERNAME_INT: {{ .Values.config.basicAuthINT.username | b64enc | quote }}
  BASIC_AUTH_PASSWORD_INT: {{ .Values.config.basicAuthINT.password | b64enc | quote }}
  BASIC_AUTH_USERNAME_ERPC: {{ .Values.config.basicAuthERPC.username | b64enc | quote }}
  BASIC_AUTH_PASSWORD_ERPC: {{ .Values.config.basicAuthERPC.password | b64enc | quote }}
  INTERPRETER_URL: {{ .Values.config.interpreterURL | b64enc | quote }}
  QN_SSO_SECRET: {{ .Values.config.qnSsoSecret | b64enc | quote }}
  JWT_SECRET: {{ .Values.config.jwtSecret | b64enc | quote }}
  BLOCKSCOUT_API_KEY: {{ .Values.config.blockscoutApiKey | b64enc | quote }}
