name: sql-exporter
version: 0.1.3
appVersion: 2.10.0
description: Prometheus exporter which allows collecting metrics from database queries, at specified time intervals
apiVersion: v1

maintainers:
  - name: AntiD2ta
  - name: nmjustinchan
