---
replicas: 1

image:
  repository: adonato/query-exporter
  pullPolicy: Always
  tag: latest

## Additional labels and annotations for the deployment resource
##
labels: {}
annotations: {}

## Additional labels and annotations for the pods
podLabels: {}
podAnnotations: {}

service:
  type: ClusterIP
  port: 80

  ## Additional labels and annotations for the service
  annotations: {}
  labels: {}

## Resources to allocate to the pods
##
resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi

## Deployment strategy
##
strategy:
  type: RollingUpdate

## Liveness and Readiness probes
##
livenessProbe:
  httpGet:
    path: /health/live
    port: 8080

readinessProbe:
  httpGet:
    path: /health/ready
    port: 8080
  initialDelaySeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3
  periodSeconds: 30

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
#
nodeSelector: {}

## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

## Affinity for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Set the security context of the pods
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context
##
securityContext:
  # runAsUser: 65534  # run as nobody user

## Arguments for the exporter binary
##
args:
  - /etc/config.yaml
  - -H
  - '0.0.0.0'
  - -LDEBUG

serviceMonitor:
  enabled: true
  scrapeInterval: 10s

## Actual configuration of the exporter, see docs https://github.com/albertodonato/query-exporter
##
config: {}
##  databases:
##    dbName:
##      dsn: postgresql://hocalhost/dbName
##      labels:
##        app: dbName
##  metrics:
##    metrics_name:
##      type: gauge
##      description:

##  queries:
##    query1:
##      databases:
##        - dbName
##      metrics: [metrics_name]
##      interval: 1h
##      sql: SQL query to execute
