apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blockscout-complete.fullname" . }}-release-name
  labels:
    {{- include "blockscout-complete.labels" . | nindent 4 }}
data:
  RELEASE_NAME: {{ .Release.Name }}
