name: charts/all

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch default branch
        run: git fetch origin ${{ github.event.repository.default_branch }}:${{ github.event.repository.default_branch }}

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.13.0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.0
        with:
          version: "v3.10.0"

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: >
          ct lint
          --config ct.yaml
          --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.9.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: |
          # Define excluded charts
          excluded_charts=(
            "autoscout"
            "chainscout"
            "cloudflare-tunnel"
            "da-indexer"
            "dshackle"
            "eth-rpc-exporter"
            "eth-tx-summary-api"
            "graph-node"
            "image-generator"
            "metabase"
            "multichain-aggregator"
            "pganalyzer"
            "quicknode-marketplace"
            "redstone-mud"
            "remix-project"
            "rpc-node"
            "smart-guessr"
            "sql-exporter"
            "swapscout"
            "tracker"
            "verification-app"
            "visualizer"
            "yopass"
            "zilliqa-validators-indexer"
          )

          # Function to check if a chart is excluded
          is_excluded() {
            local chart=$1
            for excluded in "${excluded_charts[@]}"; do
              if [[ "$chart" == "$excluded" ]]; then
                return 0
              fi
            done
            return 1
          }

          # Process each changed chart
          for chart in $(ct list-changed --config ct.yaml --target-branch ${{ github.event.repository.default_branch }}); do
            if is_excluded "$chart"; then
              echo "Skipping excluded chart: $chart"
              continue
            fi

            echo "Installing chart: $chart"
            ct install --config ct.yaml --target-branch ${{ github.event.repository.default_branch }}
          done
